/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TicTacToe */

#ifndef _Included_TicTacToe
#define _Included_TicTacToe
#ifdef __cplusplus
extern "C" {
#endif
#undef TicTacToe_FOCUS_TRAVERSABLE_UNKNOWN
#define TicTacToe_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef TicTacToe_FOCUS_TRAVERSABLE_DEFAULT
#define TicTacToe_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef TicTacToe_FOCUS_TRAVERSABLE_SET
#define TicTacToe_FOCUS_TRAVERSABLE_SET 2L
#undef TicTacToe_TOP_ALIGNMENT
#define TicTacToe_TOP_ALIGNMENT 0.0f
#undef TicTacToe_CENTER_ALIGNMENT
#define TicTacToe_CENTER_ALIGNMENT 0.5f
#undef TicTacToe_BOTTOM_ALIGNMENT
#define TicTacToe_BOTTOM_ALIGNMENT 1.0f
#undef TicTacToe_LEFT_ALIGNMENT
#define TicTacToe_LEFT_ALIGNMENT 0.0f
#undef TicTacToe_RIGHT_ALIGNMENT
#define TicTacToe_RIGHT_ALIGNMENT 1.0f
#undef TicTacToe_serialVersionUID
#define TicTacToe_serialVersionUID -7644114512714619750i64
#undef TicTacToe_serialVersionUID
#define TicTacToe_serialVersionUID 4613797578919906343i64
#undef TicTacToe_INCLUDE_SELF
#define TicTacToe_INCLUDE_SELF 1L
#undef TicTacToe_SEARCH_HEAVYWEIGHTS
#define TicTacToe_SEARCH_HEAVYWEIGHTS 1L
#undef TicTacToe_OPENED
#define TicTacToe_OPENED 1L
#undef TicTacToe_serialVersionUID
#define TicTacToe_serialVersionUID 4497834738069338734i64
#undef TicTacToe_DEFAULT_CURSOR
#define TicTacToe_DEFAULT_CURSOR 0L
#undef TicTacToe_CROSSHAIR_CURSOR
#define TicTacToe_CROSSHAIR_CURSOR 1L
#undef TicTacToe_TEXT_CURSOR
#define TicTacToe_TEXT_CURSOR 2L
#undef TicTacToe_WAIT_CURSOR
#define TicTacToe_WAIT_CURSOR 3L
#undef TicTacToe_SW_RESIZE_CURSOR
#define TicTacToe_SW_RESIZE_CURSOR 4L
#undef TicTacToe_SE_RESIZE_CURSOR
#define TicTacToe_SE_RESIZE_CURSOR 5L
#undef TicTacToe_NW_RESIZE_CURSOR
#define TicTacToe_NW_RESIZE_CURSOR 6L
#undef TicTacToe_NE_RESIZE_CURSOR
#define TicTacToe_NE_RESIZE_CURSOR 7L
#undef TicTacToe_N_RESIZE_CURSOR
#define TicTacToe_N_RESIZE_CURSOR 8L
#undef TicTacToe_S_RESIZE_CURSOR
#define TicTacToe_S_RESIZE_CURSOR 9L
#undef TicTacToe_W_RESIZE_CURSOR
#define TicTacToe_W_RESIZE_CURSOR 10L
#undef TicTacToe_E_RESIZE_CURSOR
#define TicTacToe_E_RESIZE_CURSOR 11L
#undef TicTacToe_HAND_CURSOR
#define TicTacToe_HAND_CURSOR 12L
#undef TicTacToe_MOVE_CURSOR
#define TicTacToe_MOVE_CURSOR 13L
#undef TicTacToe_NORMAL
#define TicTacToe_NORMAL 0L
#undef TicTacToe_ICONIFIED
#define TicTacToe_ICONIFIED 1L
#undef TicTacToe_MAXIMIZED_HORIZ
#define TicTacToe_MAXIMIZED_HORIZ 2L
#undef TicTacToe_MAXIMIZED_VERT
#define TicTacToe_MAXIMIZED_VERT 4L
#undef TicTacToe_MAXIMIZED_BOTH
#define TicTacToe_MAXIMIZED_BOTH 6L
#undef TicTacToe_serialVersionUID
#define TicTacToe_serialVersionUID 2673458971256075116i64
/*
 * Class:     TicTacToe
 * Method:    checkForWin
 * Signature: (IIC)Z
 */
JNIEXPORT jboolean JNICALL Java_TicTacToe_checkForWin
  (JNIEnv *, jobject, jint, jint, jchar);

/*
 * Class:     TicTacToe
 * Method:    isDraw
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_TicTacToe_isDraw
  (JNIEnv *, jobject);

/*
 * Class:     TicTacToe
 * Method:    resetGame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_TicTacToe_resetGame
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
